<!DOCTYPE html>
<html lang="vi">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Weather & Life</title>

  <script src="https://cdn.tailwindcss.com"></script>
  <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/remixicon/4.6.0/remixicon.min.css" rel="stylesheet">
  <link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />
  <script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/echarts/5.5.0/echarts.min.js"></script>

  <style>
    .weather-card { backdrop-filter: blur(8px); background: rgba(255, 255, 255, 0.8); transition: transform 0.3s ease; }
    .weather-card:hover { transform: scale(1.05); }
    #map { height: 400px; }
  </style>
</head>
<body class="bg-gray-50 font-sans">

<header class="fixed w-full top-0 z-50 bg-white shadow">
  <nav class="container mx-auto px-6 py-4 flex items-center justify-between">
    <div class="text-2xl font-['Pacifico'] text-blue-500">Weather & Life</div>
    <div class="flex gap-6">
      <a href="#weather" class="hover:text-blue-500">Thời tiết</a>
      <a href="#sos" class="hover:text-blue-500">SOS</a>
      <a href="#plants" class="hover:text-blue-500">Cây trồng</a>
      <a href="#alerts" class="hover:text-blue-500">Cảnh báo</a>
    </div>
    <div class="relative">
      <input id="locationSearch" type="text" placeholder="Tìm kiếm địa điểm..." class="pl-10 pr-4 py-2 rounded-full bg-gray-100 w-64">
      <i class="ri-search-line absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"></i>
    </div>
  </nav>
</header>

<main class="pt-20">
  <section class="h-[600px] bg-cover bg-center flex items-center justify-center text-white" style="background-image: url('https://source.unsplash.com/1920x600/?weather,landscape');">
    <div class="text-center">
      <h1 class="text-5xl font-bold mb-4">Theo dõi thời tiết thông minh</h1>
      <p class="text-xl mb-6">Dự báo chính xác - Bảo vệ cuộc sống</p>
      <button class="bg-blue-500 text-white px-6 py-3 rounded-full hover:bg-blue-600" onclick="locateUser()">Xem thời tiết của bạn</button>
    </div>
  </section>

  <section class="container mx-auto px-6 py-16 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
    <div class="weather-card p-6 rounded-lg shadow">
      <i class="ri-temp-hot-line text-blue-500 text-3xl mb-4"></i>
      <h3 class="text-xl font-semibold mb-2">Thời tiết địa phương</h3>
      <p class="text-gray-600 mb-4">Xem chi tiết nhiệt độ, độ ẩm, gió tại vị trí của bạn.</p>
      <button class="text-blue-500 hover:underline">Xem chi tiết</button>
    </div>
    <div class="weather-card p-6 rounded-lg shadow">
      <i class="ri-alarm-warning-line text-red-500 text-3xl mb-4"></i>
      <h3 class="text-xl font-semibold mb-2">SOS Khẩn cấp</h3>
      <p class="text-gray-600 mb-4">Gửi tín hiệu khẩn cấp đến đội cứu hộ.</p>
      <button class="text-red-500 hover:underline">Gọi ngay</button>
    </div>
    <div class="weather-card p-6 rounded-lg shadow">
      <i class="ri-plant-line text-green-500 text-3xl mb-4"></i>
      <h3 class="text-xl font-semibold mb-2">Gợi ý cây trồng</h3>
      <p class="text-gray-600 mb-4">Tư vấn cây trồng phù hợp với thời tiết.</p>
      <button class="text-green-500 hover:underline">Xem gợi ý</button>
    </div>
    <div class="weather-card p-6 rounded-lg shadow">
      <i class="ri-thunderstorms-line text-yellow-500 text-3xl mb-4"></i>
      <h3 class="text-xl font-semibold mb-2">Cảnh báo thiên tai</h3>
      <p class="text-gray-600 mb-4">Cảnh báo nguy hiểm thiên tai sớm nhất.</p>
      <button class="text-yellow-500 hover:underline">Xem cảnh báo</button>
    </div>
  </section>

  <section class="container mx-auto px-6 py-16">
    <h2 class="text-3xl font-bold text-center mb-6">Dự báo 7 ngày tới</h2>
    <div id="weatherChart" class="h-[400px] mb-12"></div>
    <h2 class="text-3xl font-bold text-center mb-6">Bản đồ tương tác</h2>
    <div id="map" class="rounded-lg shadow"></div>
  </section>
</main>

<footer class="bg-gray-900 text-white py-8 text-center">
  &copy; 2025 Weather & Life. Tất cả quyền được bảo lưu.
</footer>

<script>
  document.addEventListener("DOMContentLoaded", () => {
    const chart = echarts.init(document.getElementById("weatherChart"));
    chart.setOption({
      tooltip: { trigger: "axis" },
      xAxis: { type: "category", data: ["T2", "T3", "T4", "T5", "T6", "T7", "CN"] },
      yAxis: { type: "value" },
      series: [{
        name: "Nhiệt độ", type: "line", data: [28, 29, 31, 30, 29, 27, 28], smooth: true,
        lineStyle: { color: "#1E90FF" }, areaStyle: { color: "#E0F2FF" }
      }]
    });

    const map = L.map('map').setView([16.0471, 108.2062], 6);
    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { attribution: '&copy; OpenStreetMap contributors' }).addTo(map);

    window.locateUser = () => {
      map.locate({ setView: true, maxZoom: 12 });
      map.on('locationfound', e => {
        L.marker(e.latlng).addTo(map).bindPopup("Bạn đang ở đây!").openPopup();
      });
    }
  });
</script>

</body>
</html>
